[package]
name = "nbssh"
version = "0.8.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
repository = "https://github.com/nicholasbishop/nbssh-rs"
license = "Apache-2.0"
description = "Simple SSH utility module"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
subprocess = "0.1"

[dev-dependencies]
serde_test = "1.0"
