[package]
name = "nbssh"
version = "0.4.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
repository = "https://github.com/nicholasbishop/nbssh-rs"
license = "Apache-2.0"
description = "Simple SSH utility module"

[dependencies]
serde = "1.0"
subprocess = "0.1"
